name: retail_app
description: A retail management app with sales tracking, inventory management, and customer loyalty features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  path_provider: ^2.0.15
  intl: ^0.18.1
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data.json